version: '3'

services:
  redis:
    image: redis:latest
    container_name: tipster_redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - "6380:6379"
    volumes:
      - ./data/redis:/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  vosk:
    container_name: tipster_vosk
    build: 
      dockerfile: Dockerfile.vosk
      context: .
    ports:
      - "2701:2700"
  
  mail:
    image: maildev/maildev
    container_name: tipster_mail
    restart: always
    environment:
      - TZ=Asia/Omsk
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - '1080:1080'
      - '1025:1025'

  database:
    image: postgres:13.3
    container_name: tipster_db
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./data/pgs-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
